languageCode: en-us
baseURL: https://CasteHappy.github.io/TheDoorOfFate/
title: CasteHappy
paginate: 5
theme: PaperMod
pluralizelisttitles: false
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
relativeURLs: true
#googleAnalytics:

minify:
  disableXML: true
  minifyOutput: false

params:
  #env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: CasteHappy
  description: "Online home of Javier (Caste) Castellanos, video editor, YTPMV enthusiast, FGC competitor and piracy apologist."
  keywords: [Blog, Portfolio, Video Editing, YTPMV]
  author: Caste
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "CasteHappy"
    icon: "/TheDoorOfFate/images/crosshair.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "The Door of Fate, 
    shall open"
    subtitle: "Online home of Javier (Caste) Castellanos, video editor, YTPMV enthusiast,
    FGC competitor and piracy apologist."
    imageUrl: "/TheDoorOfFate/images/door_of_fate.gif"
    imageWidth: 250
    imageHeight: 250
    imageTitle: "goldman-pixel"
    buttons:
      - name: Blogs
        url: blogs
      - name: Portfolio
        url: portfolio
      - name: Tutorials
        url: tutorials

  # home-info mode
  homeInfoParams:
    Title: "The Door of Fate,
     shall open"
    Content: "Online home of Javier (Caste) Castellanos, video editor, YTPMV enthusiast,
    FGC competitor and piracy apologist."

  socialIcons:
    - name: youtube
      url: "http://youtube.com/castehappy"
      #name: twitter
      #url: "https://twitter.com/CasteHappy"
    - name: buymeacoffee
      url: "https://ko-fi.com/castehappy"

  #analytics:
    #google:
      #SiteVerificationTag: "XYZabc"
    #bing:
      #SiteVerificationTag: "XYZabc"
    #yandex:
      #SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifer: tutorials
      name: Tutorials
      url: tutorials/
      weight: 3
    - identifier: about
      name: About
      url: about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: blogs/
      weight: 1
    - identifier: portfolio
      name: Portfolio
      url: portfolio/
      weight: 2
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
